apiVersion: apps/v1
kind: Deployment
metadata:
  name: NAME-deployment
  labels:
    app: NAME
spec:
  replicas: 3
  selector:
    matchLabels:
      app: NAME
  template:
    metadata:
      labels:
        app: NAME
    spec:
      containers:
      - name: web
        image: kedahs03/website06
        ports:
        - containerPort: 80
