apiVersion: v1
kind: Service
metadata:
  name: faizal-service
spec:
  type: NodePort
  selector:
    myapp: faizal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: faizal
  labels:
    myapp: faizal
spec:
  replicas: 3
  selector:
    matchLabels:
      myapp: faizal
  template:
    metadata:
      labels:
        myapp: faizal
    spec:
      containers:
      - name: web
        image: kedahs03/frozenyogurtshop
        ports:
        - containerPort: 80
